Standardized blood fix
Modified-MW-DF/modified-MDF-Launcher pull request #1
Opened 2017-06-27 15:32 UTC by tali713

Fixing error in token replacement for standardized blood, as noted by Nanaki on discord.

2017-06-27 23:16 UTC, Amostubal requested changes
Needs to be same length or eof will bug out.

2017-06-28 00:49 UTC, tali713 commented
Aha, okay, I'm working on a mac most of the time so I haven't gotten a build setup going yet.  Hopefully this is now correct.

2017-06-28 05:37 UTC, Amostubal approved these changes

2017-06-28 05:38 UTC, Amostubal commented
No problem I don't know how I let that error sneak in lol... I can rebuild this side prior to a release.

2017-06-28 05:38 UTC, merged